; PlatformIO Project Configuration
; Two boards: CubeCell (I2C Slave) and NodeMCU (I2C Master)

[env:cubecell]
platform = heltec-cubecell
board = cubecell_board_v2
framework = arduino
monitor_speed = 115200
build_src_filter = +<cubecell_main.cpp>
build_flags =
    -D REGION_EU433

[env:nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = +<nodemcu_main.cpp>
