; CubeCell TX -> LoRa -> CubeCell RX -> Serial -> NodeMCU -> CRSF -> FC

[env:cubecell_rx]
platform = heltec-cubecell
board = cubecell_board_v2
framework = arduino
monitor_speed = 115200
build_src_filter = +<cubecell_rx.cpp>
build_flags = -D REGION_EU433

[env:cubecell_tx]
platform = heltec-cubecell
board = cubecell_board_v2
framework = arduino
monitor_speed = 115200
build_src_filter = +<cubecell_tx.cpp>
build_flags = -D REGION_EU433

[env:nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = +<nodemcu_main.cpp>
lib_deps = alfredosystems/AlfredoCRSF
